"""Theory answer library — model answers per topic per difficulty."""
from __future__ import annotations
from app.services.interview_engine import THEORY_TOPICS, question_set, answer_guide

def _a(qid, question, direct, points, example, formula, difficulty, topic):
    return {"id": qid, "question": question, "difficulty": difficulty, "topic": topic,
            "direct_answer": direct, "key_points": points,
            "example": example, "writing_formula": formula}

LIBRARY: dict[str, dict[str, list[dict]]] = {
  "Data Structures": {
    "Easy": [
      _a("lib-ds-e-1","What is a stack and where is it used?",
         "A stack is a linear LIFO (Last-In, First-Out) data structure where elements are added and removed from the same end called the top.",
         ["Push adds to top in O(1); pop removes from top in O(1).",
          "Used for: function call stack, undo/redo, expression evaluation, DFS traversal.",
          "Overflow occurs when pushing to a full stack; underflow when popping an empty stack.",
          "Can be implemented using an array (static) or linked list (dynamic)."],
         "Browser back-button: visiting pages pushes URLs; clicking back pops them.",
         "Define → Operations → Time complexity → Real use case → Edge case",
         "Easy","Data Structures"),
      _a("lib-ds-e-2","What is a queue and how does it differ from a stack?",
         "A queue is a FIFO (First-In, First-Out) data structure where insertion (enqueue) happens at the rear and deletion (dequeue) at the front.",
         ["Stack is LIFO; queue is FIFO — the fundamental difference.",
          "Queue use cases: BFS, task scheduling, printer spooling, message queues.",
          "Variants: circular queue (no wasted space), deque (both ends), priority queue.",
          "Enqueue and dequeue are O(1) with linked list or circular array."],
         "CPU process scheduling: jobs enter queue when created and are served in arrival order.",
         "Define → Contrast with stack → Operations → Variants → Use case",
         "Easy","Data Structures"),
      _a("lib-ds-e-3","Explain arrays vs linked lists. When would you choose each?",
         "Arrays store elements in contiguous memory with O(1) random access. Linked lists store elements as nodes with pointers, allowing O(1) insertion/deletion at known positions.",
         ["Array: O(1) access, O(n) insert/delete in middle, fixed or amortized-resize size.",
          "Linked list: O(n) access, O(1) insert/delete at head, dynamic size, extra pointer memory.",
          "Choose array when: frequent reads by index, cache performance matters, size is known.",
          "Choose linked list when: frequent insertions/deletions, size is unknown, no random access needed."],
         "A music playlist implemented as linked list allows O(1) song insertion mid-list vs rebuilding array.",
         "Define both → Compare access/insert/delete complexity → Memory → Decision rule",
         "Easy","Data Structures"),
    ],
    "Medium": [
      _a("lib-ds-m-1","Design an LRU cache. What data structures would you use and why?",
         "An LRU (Least Recently Used) cache evicts the least recently accessed item when capacity is reached. Use a HashMap + Doubly Linked List for O(1) get and put.",
         ["HashMap maps key → node for O(1) lookup.",
          "Doubly linked list maintains access order: MRU at head, LRU at tail.",
          "On get: move accessed node to head.",
          "On put: add to head; if capacity exceeded, remove tail node and its map entry.",
          "Space complexity O(capacity)."],
         "get(key): look up in map → if found, move node to head, return val. put(key,val): if exists update and move to head; else create node at head, add to map; if over capacity, remove tail.",
         "State the eviction policy → Data structures chosen → Why each → Walkthrough put/get → Edge case (capacity=0)",
         "Medium","Data Structures"),
      _a("lib-ds-m-2","How do you detect a cycle in a directed graph?",
         "Use DFS with three-color marking: WHITE (unvisited), GRAY (in current DFS path), BLACK (fully processed). A GRAY→GRAY back edge indicates a cycle.",
         ["Color each node; start DFS from each unvisited node.",
          "If DFS reaches a GRAY neighbor, a cycle exists.",
          "Alternative: Kahn's algorithm — if topological sort cannot include all nodes, a cycle exists.",
          "For undirected graphs: back edge in DFS tree indicates cycle (simpler with visited set)."],
         "Graph: A→B→C→A. DFS from A: gray A, gray B, gray C. C's neighbor A is gray → cycle detected.",
         "State approach → Three colors explained → DFS walkthrough → Alternative (Kahn's) → Complexity",
         "Medium","Data Structures"),
    ],
    "Hard": [
      _a("lib-ds-h-1","Explain the difference between BFS and DFS. When would you use each on a graph?",
         "BFS explores level by level using a queue; DFS explores as deep as possible using a stack (or recursion). BFS finds shortest path in unweighted graphs; DFS is useful for cycle detection, topological sort, and exhaustive search.",
         ["BFS: O(V+E) time, O(V) space (queue stores entire level); optimal for shortest path.",
          "DFS: O(V+E) time, O(V) space (call stack); optimal for cycle detection, SCC, topological sort.",
          "BFS preferred: shortest path in unweighted graph, level-order tree traversal, finding all nodes within k hops.",
          "DFS preferred: maze solving, topological sort, SCC (Tarjan/Kosaraju), detecting back edges."],
         "Social network: BFS to find shortest connection (degrees of separation). Dependency resolver: DFS topological sort to order build steps.",
         "Define both → Data structure used → Space/time → When to use BFS → When to use DFS → Example",
         "Hard","Data Structures"),
    ],
  },
  "DBMS & SQL": {
    "Easy": [
      _a("lib-db-e-1","What is a primary key and why is it important?",
         "A primary key is a column (or combination) that uniquely identifies each row in a table. It enforces entity integrity and is automatically indexed.",
         ["Must be unique and NOT NULL — both constraints are enforced automatically.",
          "Every table should have a primary key for data integrity and efficient lookups.",
          "Natural key: meaningful business data (email). Surrogate key: system-generated (UUID, auto-increment ID).",
          "Surrogate keys are preferred when natural keys can change or are complex."],
         "Users table: user_id INT PRIMARY KEY AUTO_INCREMENT. Each user gets a unique system-assigned ID regardless of changing emails.",
         "Define → Constraints it enforces → Natural vs Surrogate → Trade-off",
         "Easy","DBMS & SQL"),
      _a("lib-db-e-2","What is the difference between WHERE and HAVING?",
         "WHERE filters rows before aggregation; HAVING filters groups after aggregation. WHERE cannot use aggregate functions; HAVING can.",
         ["WHERE is applied to individual rows; HAVING is applied to grouped rows.",
          "HAVING is used after GROUP BY; WHERE is used before GROUP BY.",
          "You can use both in one query: WHERE filters raw rows first, then GROUP BY groups them, then HAVING filters groups.",
          "Common mistake: using HAVING when WHERE suffices — HAVING is slower as it operates post-aggregation."],
         "SELECT dept, AVG(salary) FROM emp WHERE active=1 GROUP BY dept HAVING AVG(salary)>50000. WHERE removes inactive employees first; HAVING keeps only high-paying departments.",
         "Define both → Order of execution → What each can reference → Common mistake → Example",
         "Easy","DBMS & SQL"),
    ],
    "Medium": [
      _a("lib-db-m-1","How does an index work and what are the trade-offs of adding one?",
         "An index is a data structure (usually B-tree) that stores sorted copies of column values with pointers to rows, enabling O(log n) lookup instead of O(n) full scan.",
         ["B-tree index: sorted → supports range queries, equality, ORDER BY.",
          "Hash index: O(1) equality lookup but no range queries.",
          "Trade-offs: faster reads BUT slower writes (index must be updated on INSERT/UPDATE/DELETE) and extra storage.",
          "Add index when: column is frequently in WHERE, JOIN, or ORDER BY; column has high cardinality; table is large.",
          "Avoid: low-cardinality columns (boolean), frequently updated columns, tiny tables."],
         "E-commerce orders table 10M rows. Without index on customer_id: full scan on every lookup. With index: O(log n) — 23 comparisons instead of 10M.",
         "What it stores → B-tree mechanics → Read speedup → Write cost → When to add → When to avoid",
         "Medium","DBMS & SQL"),
      _a("lib-db-m-2","Explain ACID properties with a real-world example.",
         "ACID ensures reliable database transactions. A=Atomicity (all or nothing), C=Consistency (valid state before/after), I=Isolation (concurrent transactions don't interfere), D=Durability (committed data persists).",
         ["Atomicity: bank transfer either debits AND credits, or neither — no partial state.",
          "Consistency: constraints (foreign key, check, not null) hold before and after transaction.",
          "Isolation: two concurrent transfers don't see each other's intermediate state.",
          "Durability: after COMMIT, data survives crashes (via WAL/journaling).",
          "Isolation levels trade consistency for performance: Read Uncommitted → Read Committed → Repeatable Read → Serializable."],
         "Bank transfer ₹1000 from A to B: BEGIN; UPDATE accounts SET bal=bal-1000 WHERE id=A; UPDATE accounts SET bal=bal+1000 WHERE id=B; COMMIT. If crash between updates, ROLLBACK restores both.",
         "Define each letter → Real transaction example → Show each property in action → Isolation levels",
         "Medium","DBMS & SQL"),
    ],
    "Hard": [
      _a("lib-db-h-1","What is MVCC and how does it enable concurrent reads without blocking?",
         "Multi-Version Concurrency Control (MVCC) stores multiple versions of each row with timestamps/transaction IDs. Readers see a consistent snapshot without locking; writers create new versions instead of overwriting.",
         ["Each row version has xmin (created by) and xmax (deleted by) transaction IDs.",
          "A reader's snapshot sees only rows where xmin ≤ snapshot_txid < xmax.",
          "Writers don't block readers and readers don't block writers — only write-write conflicts require locks.",
          "Dead tuples accumulate and must be cleaned by VACUUM (PostgreSQL) or equivalent.",
          "MVCC enables snapshot isolation which prevents dirty reads and non-repeatable reads."],
         "T1 reads user row (sees v1). T2 updates name (creates v2, marks v1 xmax=T2). T1 still reads v1 (its snapshot predates T2). No blocking, no dirty read.",
         "Define versioning → xmin/xmax mechanics → Why no read-write blocking → Dead tuple cost → VACUUM → Isolation level provided",
         "Hard","DBMS & SQL"),
    ],
  },
  "Operating Systems": {
    "Easy": [
      _a("lib-os-e-1","What is the difference between a process and a thread?",
         "A process is an independent program in execution with its own memory space. A thread is a lightweight unit of execution within a process, sharing the process's memory.",
         ["Process: own address space, file descriptors, heap, stack. Isolated — crash doesn't affect others.",
          "Thread: shares address space, heap, file descriptors with sibling threads. Own stack and registers.",
          "Creating a process (fork) is expensive; creating a thread is cheap.",
          "Communication: processes use IPC (pipes, sockets, shared memory); threads use shared memory directly.",
          "Thread safety matters because threads share heap — concurrent writes need synchronization."],
         "Web server: each request handled by a thread (shared connection pool, cache). Fork-based server: each request in isolated process (safer but slower).",
         "Define both → What is shared vs private → Creation cost → Communication → When to use each",
         "Easy","Operating Systems"),
      _a("lib-os-e-2","What is a deadlock and what are the four conditions for it to occur?",
         "A deadlock is a state where two or more processes are permanently blocked, each waiting for a resource held by another.",
         ["1. Mutual Exclusion: resource can only be held by one process at a time.",
          "2. Hold and Wait: process holds a resource while waiting for another.",
          "3. No Preemption: resources cannot be forcibly taken from a process.",
          "4. Circular Wait: processes form a cycle, each waiting for the next.",
          "Prevention: eliminate one condition (e.g., request all resources at once to break hold-and-wait).",
          "Avoidance: Banker's algorithm checks if granting a request leads to unsafe state."],
         "T1 holds Lock A, waits for Lock B. T2 holds Lock B, waits for Lock A. Circular wait → deadlock. Fix: always acquire locks in the same global order.",
         "Define → Four conditions → Example → Prevention strategy → Detection/recovery",
         "Easy","Operating Systems"),
    ],
    "Medium": [
      _a("lib-os-m-1","Explain virtual memory. How does paging work?",
         "Virtual memory gives each process an illusion of a large private address space, decoupled from physical RAM. Paging divides virtual and physical memory into fixed-size pages/frames for mapping.",
         ["Page table maps virtual page numbers to physical frame numbers.",
          "On access: MMU translates virtual → physical. If page not in RAM → page fault → OS loads from disk.",
          "TLB caches recent translations for O(1) access instead of O(1) page table walk.",
          "Benefits: process isolation, more processes than RAM fits, memory protection via permission bits.",
          "Trade-off: page faults are expensive (disk I/O ~1ms vs RAM ~100ns)."],
         "Process accesses address 0x4000. MMU splits into page number 4 and offset 0x000. Looks up page table: frame 7. Physical address = frame 7 * page_size + 0x000.",
         "What virtual memory provides → Paging mechanics → Page fault → TLB → Benefits → Cost",
         "Medium","Operating Systems"),
    ],
    "Hard": [
      _a("lib-os-h-1","What are race conditions and how do you prevent them? Explain mutex vs semaphore.",
         "A race condition occurs when program behaviour depends on the non-deterministic timing of concurrent operations accessing shared state. Prevented by synchronization primitives.",
         ["Mutex (MUTual EXclusion): binary lock — only one thread at a time. Used for protecting critical sections.",
          "Semaphore: counter allowing N concurrent accesses. Binary semaphore ≈ mutex. Counting semaphore for resource pools.",
          "Mutex difference: ownership — only the locking thread can unlock. Semaphore has no ownership.",
          "Condition variable: wait for a condition within a mutex (producer-consumer).",
          "Deadlock risk: always acquire multiple locks in the same global order.",
          "Lock-free alternative: CAS (Compare-And-Swap) atomic operations for simple shared counters."],
         "Counter++ is not atomic: read(0)→add→write(1) can race with another thread doing same → both write 1 instead of 2. Fix: mutex around the operation or atomic increment.",
         "Define race condition → Example → Mutex mechanics → Semaphore → Key difference → When each → Deadlock risk",
         "Hard","Operating Systems"),
    ],
  },
  "Computer Networks": {
    "Easy": [
      _a("lib-cn-e-1","What happens when you type a URL in the browser and press Enter?",
         "Browser resolves DNS, establishes TCP connection, performs TLS handshake (for HTTPS), sends HTTP request, receives response, and renders the page.",
         ["1. DNS: browser cache → OS cache → resolver → root → TLD → authoritative → IP returned.",
          "2. TCP: 3-way handshake (SYN, SYN-ACK, ACK) establishes connection.",
          "3. TLS (HTTPS): certificate exchange, key negotiation, encrypted channel established.",
          "4. HTTP GET request sent; server returns HTML with status 200.",
          "5. Browser parses HTML, requests CSS/JS/images (may open additional connections).",
          "6. Page renders as resources arrive."],
         "Entire flow for https://google.com: DNS resolves to 142.250.x.x → TCP to port 443 → TLS handshake → GET / HTTP/2 → 200 OK + HTML → browser renders.",
         "DNS → TCP connection → TLS → HTTP request → Response → Render → Each step's purpose",
         "Easy","Computer Networks"),
    ],
    "Medium": [
      _a("lib-cn-m-1","Explain TCP vs UDP. When would you choose each?",
         "TCP is connection-oriented with guaranteed ordered delivery, flow control, and congestion control. UDP is connectionless with no guarantees but minimal overhead.",
         ["TCP: 3-way handshake, sequence numbers, ACKs, retransmission, flow window. Reliable but ~20-40% overhead.",
          "UDP: no connection, no ACK, no ordering, no retransmission. Low latency.",
          "TCP use cases: HTTP/HTTPS, file transfer (FTP), email (SMTP), database connections.",
          "UDP use cases: DNS (one small packet), video streaming, online gaming, VoIP, WebRTC.",
          "Modern trend: QUIC runs over UDP but implements reliability at application layer for HTTP/3."],
         "Video call: UDP preferred — a dropped frame is better than waiting for retransmission causing stutter. File download: TCP preferred — every byte must arrive correctly.",
         "TCP guarantees → UDP simplicity → Overhead comparison → TCP use cases → UDP use cases → QUIC context",
         "Medium","Computer Networks"),
    ],
    "Hard": [
      _a("lib-cn-h-1","How does TLS work? Explain the handshake process.",
         "TLS (Transport Layer Security) provides encryption, authentication, and integrity. The handshake establishes a shared secret and verifies the server's identity before data flows.",
         ["1. ClientHello: client sends TLS version, cipher suites, random nonce.",
          "2. ServerHello: server selects cipher, sends certificate (public key + CA signature).",
          "3. Certificate verification: client validates cert against trusted CA store.",
          "4. Key exchange: client and server use ECDHE to derive pre-master secret without transmitting it.",
          "5. Both derive session keys from random nonces + pre-master secret.",
          "6. Finished: both sides confirm handshake with MAC; data now flows encrypted.",
          "TLS 1.3 reduces to 1-RTT (or 0-RTT for resumption)."],
         "HTTPS bank login: certificate proves server is really mybank.com (not a MITM). ECDHE means even if long-term key is later stolen, past sessions remain secret (forward secrecy).",
         "Purpose → ClientHello → ServerHello → Certificate validation → Key exchange (ECDHE) → Session keys → Forward secrecy",
         "Hard","Computer Networks"),
    ],
  },
  "OOP & Design": {
    "Easy": [
      _a("lib-oop-e-1","Explain the four pillars of OOP.",
         "The four pillars are Encapsulation, Abstraction, Inheritance, and Polymorphism (EAIP). Together they promote modular, reusable, maintainable code.",
         ["Encapsulation: bundle data and methods; restrict direct access via private/protected. Reduces coupling.",
          "Abstraction: expose only essential interface; hide implementation details. Reduces complexity.",
          "Inheritance: child class inherits fields/methods of parent. Promotes reuse but creates tight coupling.",
          "Polymorphism: one interface, multiple implementations. Runtime (method override) or compile-time (overload).",
          "Prefer composition over inheritance when behaviour varies independently of type."],
         "BankAccount (base): balance, deposit(), withdraw(). SavingsAccount (child): adds interest_rate, calculateInterest(). Polymorphism: accounts.forEach(a -> a.deposit(100)) works for all types.",
         "Each pillar defined → Code example → Benefit → Common pitfall → Composition vs inheritance note",
         "Easy","OOP & Design"),
    ],
    "Medium": [
      _a("lib-oop-m-1","Explain SOLID principles with one example each.",
         "SOLID is five design principles for clean OOP: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.",
         ["S - SRP: UserService should only manage users, not send emails (separate EmailService).",
          "O - OCP: Add new shapes by creating new classes, not modifying existing Shape.area() logic.",
          "L - LSP: Rectangle subclass must not break code expecting a Shape — area() must still hold.",
          "I - ISP: IWorker should split into IWorkable and IEatable; robots implement only IWorkable.",
          "D - DIP: OrderService depends on IPaymentGateway interface, not StripePayment concretely."],
         "Violation: God class UserManager that registers, authenticates, sends emails, generates reports. Fix: split by responsibility — AuthService, NotificationService, ReportService.",
         "One sentence per principle → Violation example → Correct example → Why it matters",
         "Medium","OOP & Design"),
    ],
    "Hard": [
      _a("lib-oop-h-1","Compare monolithic vs microservices architecture. When would you choose each?",
         "A monolith is a single deployable unit with all functionality. Microservices split functionality into independently deployable services communicating via APIs.",
         ["Monolith pros: simple development, deployment, debugging; no network latency between components; ACID transactions easy.",
          "Monolith cons: scaling requires scaling the whole app; one bug can crash everything; tech stack locked.",
          "Microservices pros: independent scaling, independent deployment, polyglot tech, fault isolation.",
          "Microservices cons: network latency, distributed transactions (saga pattern), service discovery, observability complexity.",
          "Choose monolith: early-stage product, small team, tight deadlines, unclear domain boundaries.",
          "Choose microservices: proven domain model, large teams, different scaling needs per service, regulatory isolation."],
         "Netflix migrated from monolith to microservices to scale the recommendations service independently from billing. But Segment moved back to monolith when microservice complexity exceeded benefits.",
         "Define both → Monolith trade-offs → Microservices trade-offs → Decision criteria → Real examples",
         "Hard","OOP & Design"),
    ],
  },
  "System Design": {
    "Easy": [
      _a("lib-sd-e-1","What is horizontal vs vertical scaling?",
         "Vertical scaling (scale up) adds more resources to a single machine. Horizontal scaling (scale out) adds more machines to distribute load.",
         ["Vertical: bigger CPU, more RAM. Simple but has hardware limits and single point of failure.",
          "Horizontal: add more nodes behind a load balancer. Theoretically unlimited but requires stateless design.",
          "Stateless services scale horizontally easily; stateful services (sessions, DB) need extra work (sticky sessions, distributed cache, DB sharding).",
          "Most modern web services scale horizontally with stateless app servers and separate databases."],
         "Database at 80% CPU: vertical → upgrade to larger instance (quick fix). App server at limit: horizontal → add instances behind load balancer (sustainable).",
         "Define both → Limits of each → What makes horizontal hard (state) → When to use each",
         "Easy","System Design"),
    ],
    "Medium": [
      _a("lib-sd-m-1","How would you design a URL shortener?",
         "A URL shortener maps a short code to a long URL. Core components: hash generation, storage (key-value), redirect service, and analytics.",
         ["1. API: POST /shorten {url} → {short_code}. GET /{code} → 301/302 redirect.",
          "2. Hash: base62 encode a counter or random 7 chars → 62^7 = ~3.5 trillion unique codes.",
          "3. Storage: key-value store (Redis for cache, DynamoDB/Cassandra for persistence). Schema: code → {long_url, created_at, clicks}.",
          "4. Redirect: 301 (permanent, cached) for public URLs; 302 (temporary) for analytics tracking.",
          "5. Scale: read-heavy → cache hot URLs in Redis. Write: counter in Redis with DB persistence.",
          "6. Custom aliases: store user-defined codes, check uniqueness first."],
         "bit.ly/abc123 → Redis lookup → if miss, DynamoDB → 302 to long URL. Analytics: async increment click counter in background.",
         "Clarify requirements → API design → Hash/code generation → Storage choice → Redirect type → Scaling → Edge cases (custom URL, expiry)",
         "Medium","System Design"),
    ],
    "Hard": [
      _a("lib-sd-h-1","How would you design a distributed rate limiter?",
         "A distributed rate limiter restricts request frequency per user/API key across multiple servers using shared state.",
         ["Algorithms: Token Bucket (smooth bursts), Sliding Window Counter (accurate), Fixed Window (simple, edge bursts), Leaky Bucket (constant rate).",
          "Distributed state: Redis with atomic INCR + EXPIRE, or Redis sorted set for sliding window.",
          "Token Bucket in Redis: GET remaining_tokens; if >0, DECR; else reject. Refill via TTL or background job.",
          "Sliding window: Redis ZADD with timestamp; ZCOUNT in window; ZREMRANGEBYSCORE to clean old entries.",
          "Placement: at API gateway (centralized) or per-service (decentralized with Redis).",
          "Edge cases: Redis unavailable → fail open or fail closed? Network partitions → local fallback counter."],
         "100 req/min per user. Sliding window: on each request add timestamp to sorted set, count entries in last 60s, reject if ≥100, else allow and trim old entries. Redis script for atomicity.",
         "Clarify (per user? per IP? global?) → Algorithm options → Redis implementation → Atomicity → Failure modes → Placement",
         "Hard","System Design"),
    ],
  },
  "Behavioral": {
    "Easy": [
      _a("lib-beh-e-1","Tell me about yourself.",
         "A structured 90-second pitch: current role/background → key skills/achievements → why this role.",
         ["1. Current: one sentence on current role and main responsibility.",
          "2. Achievement: one quantified result you are proud of.",
          "3. Skills: two or three technical strengths relevant to the role.",
          "4. Transition: why you are interested in this role/company specifically.",
          "Keep it under 90 seconds. Practice out loud — it should sound natural, not recited.",
          "Avoid: life history, salary talk, personal details unrelated to the role."],
         "'I am currently a backend engineer at X where I own the payments service processing ₹50Cr daily. Before that I built the recommendation engine that improved CTR by 18%. I am excited about this role because your scale challenges on distributed systems match exactly what I want to work on next.'",
         "Current role → Key achievement → Relevant skills → Why this company/role",
         "Easy","Behavioral"),
    ],
    "Medium": [
      _a("lib-beh-m-1","Tell me about a time you disagreed with your team and how you handled it.",
         "Use the STAR method. Show you can hold a principled position while remaining collaborative and data-driven.",
         ["Situation: briefly set context — what was the decision and who was involved.",
          "Task: what was at stake — performance, deadline, user impact.",
          "Action: how you raised the concern (data, prototype, written proposal); how you listened to counterarguments; what you agreed to try.",
          "Result: quantified outcome showing the decision's impact.",
          "Key signals: you used evidence not just opinion; you respected the final decision; you learned something.",
          "Avoid: making teammates look incompetent; not having a result; unresolved conflict."],
         "'Team wanted to use NoSQL for a feature requiring complex joins. I benchmarked both on realistic data showing 3× slower query time with NoSQL. Team agreed to try Postgres for a sprint. We shipped 40% faster than estimated and query time was 8ms vs 25ms estimate.'",
         "Situation → Your disagreement (data-backed) → How you raised it → How resolved → Quantified result → Lesson",
         "Medium","Behavioral"),
    ],
    "Hard": [
      _a("lib-beh-h-1","Describe a situation where you had to make a decision with incomplete information.",
         "Strong answers show structured thinking under ambiguity: what information you gathered, what you assumed and why, how you validated fast, and what you would do differently.",
         ["State the stakes clearly — what would go wrong if you waited vs decided wrong.",
          "Explain information gathering: who you consulted, what data existed, what was unavailable.",
          "Describe your decision framework: what assumptions you made explicit, what reversibility you had.",
          "Show action: what you decided, how you communicated it, how you set up a checkpoint to validate.",
          "Quantify: what happened, what you learned, what you would change.",
          "Key signal: you can make quality decisions fast while being honest about uncertainty — not paralysis, not recklessness."],
         "'Production incident at 2am, root cause unclear. I decided to roll back the last deploy rather than debug live — risking reverting a valid fix but eliminating risk of extended outage. Communicated the assumption explicitly to my manager. Rollback resolved issue in 12 min. Post-mortem confirmed root cause was the deploy.'",
         "Stakes of waiting vs deciding wrong → Information gathered → Explicit assumptions → Decision made → Validation loop → Result + lesson",
         "Hard","Behavioral"),
    ],
  },
}


def get_topics() -> list[str]:
    # Keep the library aligned with every theory topic available in interviews.
    return THEORY_TOPICS


def get_questions(topic: str, difficulty: str) -> list[dict]:
    if topic not in THEORY_TOPICS or difficulty not in ("Easy", "Medium", "Hard"):
        return []

    # The curated entries remain first; every generated interview question gets a
    # deterministic, topic-aware answer guide so users are never limited to 3 cards.
    curated = LIBRARY.get(topic, {}).get(difficulty, [])
    generated = []
    curated_text = {item["question"] for item in curated}
    for item in question_set("Software Engineer", topic, difficulty):
        if item["question"] in curated_text:
            continue
        guide = answer_guide(topic, difficulty, item["question"])
        generated.append({
            "id": f"guide-{item['id'].replace('|', '-')}",
            "question": item["question"],
            "difficulty": difficulty,
            "topic": topic,
            "direct_answer": guide["direct_answer"],
            "key_points": guide["key_points"],
            "example": guide["example"],
            "writing_formula": guide["writing_formula"],
        })
    return [*curated, *generated]


def get_question(topic: str, difficulty: str, qid: str) -> dict | None:
    for q in get_questions(topic, difficulty):
        if q["id"] == qid:
            return q
    return None
