"""MCQ quiz bank — 20 questions per topic per difficulty."""
from __future__ import annotations

def _q(id, q, opts, correct):
    return {"id": id, "question": q, "options": opts, "correct": correct}

BANK = {
  "Data Structures": {
    "Easy": [
      _q("ds-e-1","Which data structure uses LIFO ordering?",["Queue","Stack","Linked List","Tree"],1),
      _q("ds-e-2","Average time complexity of lookup in a hash table?",["O(n)","O(log n)","O(1)","O(n log n)"],2),
      _q("ds-e-3","Which traversal visits root before children?",["In-order","Post-order","Level-order","Pre-order"],3),
      _q("ds-e-4","Array vs Linked List: random access is O(1) for?",["Linked List","Both","Array","Neither"],2),
      _q("ds-e-5","A queue is a ____ data structure.",["LIFO","FIFO","Random","Sorted"],1),
      _q("ds-e-6","Which data structure would you use to implement undo functionality?",["Queue","Stack","Heap","Graph"],1),
      _q("ds-e-7","What is the time complexity of accessing an element by index in an array?",["O(n)","O(log n)","O(1)","O(n²)"],2),
      _q("ds-e-8","In a linked list, what does the last node point to?",["First node","Itself","NULL","Previous node"],2),
      _q("ds-e-9","Which operation removes from the front of a queue?",["Push","Pop","Enqueue","Dequeue"],3),
      _q("ds-e-10","What is the minimum number of nodes in a binary tree of height h?",["h","h+1","2h","h²"],1),
      _q("ds-e-11","Which data structure is ideal for BFS traversal?",["Stack","Queue","Heap","Array"],1),
      _q("ds-e-12","What is the time complexity of inserting at the beginning of a linked list?",["O(n)","O(log n)","O(1)","O(n²)"],2),
      _q("ds-e-13","A binary search tree with n nodes has height at best?",["n","n/2","log n","sqrt(n)"],2),
      _q("ds-e-14","Which of the following is NOT a linear data structure?",["Array","Linked List","Stack","Tree"],3),
      _q("ds-e-15","What is the space complexity of storing n elements in an array?",["O(1)","O(log n)","O(n)","O(n²)"],2),
      _q("ds-e-16","In a doubly linked list, each node has ____ pointer(s).",["1","2","3","4"],1),
      _q("ds-e-17","Which data structure is used to implement recursion internally?",["Queue","Stack","Heap","Graph"],1),
      _q("ds-e-18","What is the worst-case time complexity of linear search?",["O(1)","O(log n)","O(n)","O(n²)"],2),
      _q("ds-e-19","A full binary tree has every node with either ____ children.",["0 or 1","0 or 2","1 or 2","exactly 2"],1),
      _q("ds-e-20","Which data structure allows O(1) insertion and deletion at both ends?",["Array","Stack","Deque","Queue"],2),
    ],
    "Medium": [
      _q("ds-m-1","Time complexity of inserting into a balanced BST?",["O(1)","O(n)","O(log n)","O(n log n)"],2),
      _q("ds-m-2","Which data structure is best for implementing a priority queue?",["Linked List","Stack","Heap","Array"],2),
      _q("ds-m-3","What is the worst-case for quicksort?",["O(n log n)","O(n)","O(n²)","O(log n)"],2),
      _q("ds-m-4","Which graph algorithm finds shortest path in an unweighted graph?",["DFS","Dijkstra","BFS","Prim's"],2),
      _q("ds-m-5","What does amortized O(1) mean for dynamic arrays?",["Always O(1)","O(1) on average over many operations","O(n) worst case only","Never O(1)"],1),
      _q("ds-m-6","In a min-heap, the root contains?",["Maximum element","Minimum element","Median element","Random element"],1),
      _q("ds-m-7","What is the time complexity of heapify operation?",["O(1)","O(log n)","O(n)","O(n log n)"],1),
      _q("ds-m-8","Which traversal of a BST gives sorted order?",["Pre-order","In-order","Post-order","Level-order"],1),
      _q("ds-m-9","What is the time complexity of building a heap from n elements?",["O(n log n)","O(n²)","O(n)","O(log n)"],2),
      _q("ds-m-10","In a hash map, collision can be resolved by?",["Only chaining","Only open addressing","Chaining or open addressing","Sorting"],2),
      _q("ds-m-11","What is the time complexity of finding the LCA in a BST?",["O(1)","O(log n)","O(n)","O(n log n)"],1),
      _q("ds-m-12","A graph with V vertices and E edges has DFS time complexity?",["O(V)","O(E)","O(V+E)","O(V*E)"],2),
      _q("ds-m-13","Which data structure supports O(log n) rank queries?",["Hash Map","Order-Statistics Tree","Heap","Trie"],1),
      _q("ds-m-14","What is the maximum number of nodes at level l in a binary tree?",["l","2^l","2^(l-1)","l²"],1),
      _q("ds-m-15","Topological sort applies only to?",["Undirected graphs","DAGs","Weighted graphs","Complete graphs"],1),
      _q("ds-m-16","Red-Black tree guarantees height of at most?",["log n","2 log n","n/2","sqrt(n)"],1),
      _q("ds-m-17","What is the time complexity of deletion from a max-heap?",["O(1)","O(log n)","O(n)","O(n log n)"],1),
      _q("ds-m-18","Which technique reduces hash collisions?",["Smaller table","Prime table size","Integer-only keys","Fewer insertions"],1),
      _q("ds-m-19","A skip list offers ____ average search time.",["O(1)","O(log n)","O(n)","O(n log n)"],1),
      _q("ds-m-20","Union-Find data structure is used for?",["Shortest path","Cycle detection in undirected graphs","Topological sort","Heap operations"],1),
    ],
    "Hard": [
      _q("ds-h-1","Worst-case space complexity of DFS on a graph with V vertices?",["O(V)","O(E)","O(V+E)","O(V²)"],0),
      _q("ds-h-2","Which augmented BST supports O(log n) rank and select?",["AVL Tree","Red-Black Tree","Order-Statistics Tree","Splay Tree"],2),
      _q("ds-h-3","Fibonacci heap achieves decrease-key in?",["O(log n)","O(1) amortized","O(n)","O(log log n)"],1),
      _q("ds-h-4","What is the time complexity of Tarjan's SCC algorithm?",["O(V²)","O(V+E)","O(E log V)","O(V log V)"],1),
      _q("ds-h-5","B-tree of order m has at most ____ children per node.",["m","m-1","m+1","2m"],0),
      _q("ds-h-6","Which structure supports O(1) amortized push, O(1) amortized pop, and O(1) min?",["Two stacks","Stack + min-stack","Priority queue","Linked list"],1),
      _q("ds-h-7","Persistent data structures maintain?",["Mutability","Immutability","Both old and new versions","Only newest version"],2),
      _q("ds-h-8","Path compression in Union-Find achieves nearly?",["O(log n)","O(alpha(n)) per operation","O(1)","O(n)"],1),
      _q("ds-h-9","Van Emde Boas tree has insert/delete/search in?",["O(log n)","O(log log U)","O(1)","O(sqrt(U))"],1),
      _q("ds-h-10","A Treap combines?",["BST and Heap","BST and Hash","Heap and Hash","AVL and Red-Black"],0),
      _q("ds-h-11","Segment tree supports range queries in?",["O(1)","O(log n)","O(n)","O(n log n)"],1),
      _q("ds-h-12","Fenwick (BIT) tree supports prefix sum updates and queries in?",["O(1)","O(log n)","O(n)","O(sqrt n)"],1),
      _q("ds-h-13","Which algorithm finds all bridges in a graph in O(V+E)?",["Tarjan's","Kruskal's","Bellman-Ford","Prim's"],0),
      _q("ds-h-14","Amortized analysis using potential method tracks?",["Worst case only","Average case","Prepaid cost stored as potential","Best case"],2),
      _q("ds-h-15","A 2-3 tree guarantees?",["O(log n) height","O(1) search","Balanced with 2 or 3 children per node","All leaves at same depth with 2 options"],2),
      _q("ds-h-16","Suffix array construction can be done in?",["O(n²)","O(n log n)","O(n)","O(n log² n)"],2),
      _q("ds-h-17","LRU cache can be implemented with O(1) get/put using?",["Array + Stack","HashMap + Doubly Linked List","Two Queues","Trie + Heap"],1),
      _q("ds-h-18","The count of inversions in an array is related to?",["DFS","Modified merge sort","Quicksort partition","Binary search"],1),
      _q("ds-h-19","A trie storing n strings of average length m uses space?",["O(n)","O(m)","O(n*m)","O(n+m)"],2),
      _q("ds-h-20","Heavy-Light Decomposition is used to solve?",["Path queries on trees in O(log² n)","Shortest paths","MST","Cycle detection"],0),
    ],
  },
  "DBMS & SQL": {
    "Easy": [
      _q("db-e-1","Which SQL clause filters rows after aggregation?",["WHERE","GROUP BY","HAVING","ORDER BY"],2),
      _q("db-e-2","A primary key constraint enforces?",["Uniqueness only","NOT NULL only","Uniqueness and NOT NULL","Foreign key"],2),
      _q("db-e-3","Which JOIN returns all rows from both tables with NULLs for non-matches?",["INNER JOIN","LEFT JOIN","RIGHT JOIN","FULL OUTER JOIN"],3),
      _q("db-e-4","What does ACID stand for?",["Atomicity,Consistency,Isolation,Durability","Atomicity,Concurrency,Integrity,Data","Access,Consistency,Isolation,Durability","Atomicity,Consistency,Index,Durability"],0),
      _q("db-e-5","Which normal form removes transitive dependencies?",["1NF","2NF","3NF","BCNF"],2),
      _q("db-e-6","What does SELECT DISTINCT do?",["Sorts results","Returns unique rows","Filters nulls","Groups rows"],1),
      _q("db-e-7","Which SQL command removes all rows from a table without logging each row?",["DELETE","DROP","TRUNCATE","REMOVE"],2),
      _q("db-e-8","A foreign key references?",["Another column in the same table","Primary key of another table","Any column in any table","An index"],1),
      _q("db-e-9","What is the default sort order of ORDER BY?",["DESC","ASC","Random","Insertion order"],1),
      _q("db-e-10","NULL in SQL represents?",["Zero","Empty string","Unknown/missing value","False"],2),
      _q("db-e-11","Which aggregate function returns the number of rows?",["SUM","AVG","COUNT","MAX"],2),
      _q("db-e-12","What does DDL stand for?",["Data Definition Language","Data Display Language","Data Deletion Language","Database Design Language"],0),
      _q("db-e-13","Which SQL keyword avoids duplicate rows in UNION?",["UNION ALL","DISTINCT","UNION (default removes duplicates)","MERGE"],2),
      _q("db-e-14","What is a view in SQL?",["A physical copy of a table","A virtual table defined by a query","An index","A stored procedure"],1),
      _q("db-e-15","Which data type stores variable-length character strings?",["CHAR","VARCHAR","INT","BLOB"],1),
      _q("db-e-16","INNER JOIN returns?",["All rows from left table","All rows from right table","Only matching rows from both tables","All rows from both tables"],2),
      _q("db-e-17","Which SQL function returns the current date?",["NOW()","GETDATE()","CURRENT_DATE (standard SQL)","TODAY()"],2),
      _q("db-e-18","What does a composite key consist of?",["Two foreign keys","Two or more columns together forming a primary key","A primary and foreign key","Multiple indexes"],1),
      _q("db-e-19","Which clause limits the number of returned rows?",["WHERE","HAVING","LIMIT","FILTER"],2),
      _q("db-e-20","AUTO_INCREMENT is used to?",["Sort automatically","Generate unique integer on each insert","Create an index","Reference another table"],1),
    ],
    "Medium": [
      _q("db-m-1","An index speeds up reads but costs?",["Nothing","Slower reads","Slower writes and extra storage","Only storage"],2),
      _q("db-m-2","REPEATABLE READ isolation prevents?",["Nothing","Dirty reads only","Dirty reads and non-repeatable reads","Phantom reads too"],2),
      _q("db-m-3","EXPLAIN ANALYZE in PostgreSQL shows?",["Syntax errors","Actual execution plan and timings","Schema info","User privileges"],1),
      _q("db-m-4","Composite index on (A,B) accelerates queries filtering on?",["B only","A only or A+B","Neither","B then A"],1),
      _q("db-m-5","A deadlock is?",["A slow query","Circular wait where transactions hold locks each other needs","Missing index","Connection timeout"],1),
      _q("db-m-6","Which JOIN type should you use to find rows in left table with NO match in right?",["INNER JOIN","LEFT JOIN + WHERE right.id IS NULL","CROSS JOIN","FULL OUTER JOIN"],1),
      _q("db-m-7","MVCC (Multi-Version Concurrency Control) helps with?",["Compressing storage","Concurrent reads without blocking writers","Faster writes","Schema migration"],1),
      _q("db-m-8","2NF requires?",["No transitive dependencies","No partial dependencies on composite PK","All columns atomic","BCNF compliance"],1),
      _q("db-m-9","Which function returns running total in SQL window functions?",["SUM() OVER()","RUNNING_SUM()","CUMSUM()","TOTAL()"],0),
      _q("db-m-10","Optimistic locking is preferred when?",["Conflicts are frequent","Conflicts are rare","Always","Never"],1),
      _q("db-m-11","A clustered index determines?",["Which columns are indexed","Physical row order of the table","Number of indexes","Join order"],1),
      _q("db-m-12","What is sharding?",["Backup strategy","Horizontal partitioning across multiple databases","Vertical scaling","Index fragmentation"],1),
      _q("db-m-13","CAP theorem states a distributed system can guarantee at most?",["1 of 3 properties","2 of 3 properties","All 3 properties","None"],1),
      _q("db-m-14","ROLLBACK in a transaction?",["Commits changes","Undoes all changes since last COMMIT","Deletes the table","Clears indexes"],1),
      _q("db-m-15","Which SQL window function assigns a rank with gaps?",["ROW_NUMBER()","RANK()","DENSE_RANK()","NTILE()"],1),
      _q("db-m-16","N+1 query problem occurs when?",["One query returns N+1 columns","Loading N children requires N extra queries after parent query","Table has N+1 rows","Index has N+1 entries"],1),
      _q("db-m-17","A covering index?",["Contains all columns needed by the query, avoiding table lookup","Covers the entire table","Indexes NULL values","Creates a view"],0),
      _q("db-m-18","Which is TRUE about a transaction using SERIALIZABLE isolation?",["Fastest isolation level","Prevents all anomalies including phantoms","Allows dirty reads","Prevents only dirty reads"],1),
      _q("db-m-19","When would you denormalize a schema?",["To reduce storage","To eliminate redundancy","To improve read performance at the cost of redundancy","To enforce referential integrity"],2),
      _q("db-m-20","CTE (Common Table Expression) is defined using?",["DEFINE","WITH","DECLARE","TEMP"],1),
    ],
    "Hard": [
      _q("db-h-1","MVCC primarily avoids?",["Storage waste","Write-write conflicts","Read-write conflicts without locking readers","Schema changes"],2),
      _q("db-h-2","PostgreSQL default isolation level is?",["Serializable","Repeatable Read","Read Committed","Read Uncommitted"],2),
      _q("db-h-3","Horizontal partitioning addresses?",["Query complexity","Write throughput and data volume at scale","Join performance","ACID guarantees"],1),
      _q("db-h-4","Two-phase locking (2PL) guarantees?",["No deadlocks","Serializability","Snapshot isolation","Eventual consistency"],1),
      _q("db-h-5","Write-ahead logging (WAL) ensures?",["Faster writes","Durability and crash recovery","Replication","Compression"],1),
      _q("db-h-6","In distributed systems, eventual consistency means?",["Data is always consistent","Given no new writes, all nodes converge to same value eventually","Transactions never fail","Reads always see latest write"],1),
      _q("db-h-7","What is a ghost write in MVCC?",["Phantom insert visible to a snapshot that shouldn't see it","A write to a deleted row","A write without logging","An unindexed write"],0),
      _q("db-h-8","Raft consensus algorithm is used for?",["SQL parsing","Leader election and log replication in distributed systems","Index maintenance","Query optimization"],1),
      _q("db-h-9","Hash join is preferred over nested loop join when?",["One table is very small","Both tables are large and unsorted","Tables are already sorted","Indexes exist"],1),
      _q("db-h-10","A saga pattern in microservices handles?",["Distributed transactions without 2PC using compensating transactions","Schema migration","Index management","Connection pooling"],0),
      _q("db-h-11","Bitmap index is efficient when?",["Column has high cardinality","Column has low cardinality (few distinct values)","Table is large","Writes are frequent"],1),
      _q("db-h-12","The lost update problem occurs when?",["Two transactions read then write the same row overwriting each other","A transaction is rolled back","An index is missing","A join is missing"],0),
      _q("db-h-13","Column-store databases are optimized for?",["OLTP workloads","OLAP/analytical queries scanning many rows but few columns","Key-value lookups","Graph traversal"],1),
      _q("db-h-14","What does VACUUM do in PostgreSQL?",["Adds indexes","Reclaims storage from dead tuples left by MVCC","Optimizes queries","Partitions tables"],1),
      _q("db-h-15","In a distributed database, quorum reads/writes ensure?",["No latency overhead","Consistency with configurable fault tolerance","Always strong consistency","No network partitions"],1),
      _q("db-h-16","Predicate locking prevents?",["Dirty reads","Phantom reads","Lost updates","Deadlocks"],1),
      _q("db-h-17","Hash partitioning distributes rows based on?",["Row insertion time","Hash of partition key","Primary key range","Random assignment"],1),
      _q("db-h-18","A materialized view differs from a regular view in that it?",["Is always up to date","Stores results physically and must be refreshed","Is faster to define","Uses less memory"],1),
      _q("db-h-19","Consistent hashing in distributed caches minimizes?",["Cache misses","Number of keys remapped when nodes are added/removed","Query latency","Storage usage"],1),
      _q("db-h-20","The SELECT FOR UPDATE statement?",["Creates a read-only lock","Acquires an exclusive lock on rows for update","Selects and deletes","Previews an update"],1),
    ],
  },
  "Operating Systems": {
    "Easy": [
      _q("os-e-1","A process vs thread: threads share?",["Nothing","Address space","File system","CPU only"],1),
      _q("os-e-2","Virtual memory allows?",["Faster CPU","Programs to use more memory than physically available","Disk-only storage","GPU acceleration"],1),
      _q("os-e-3","Semaphore with initial value 1 acts like?",["Condition variable","Mutex","Spinlock","Monitor"],1),
      _q("os-e-4","Which scheduling can cause starvation?",["Round Robin","FIFO","Priority Scheduling","FCFS"],2),
      _q("os-e-5","Thrashing occurs when?",["CPU is 100%","Too many page faults consume all CPU time","Memory is empty","Disk I/O is fast"],1),
      _q("os-e-6","Context switch stores?",["Only the stack","Process state including registers and PC","Just the PC","Memory pages"],1),
      _q("os-e-7","Which is a non-preemptive scheduling algorithm?",["Round Robin","FCFS","SRT","Multilevel Queue"],1),
      _q("os-e-8","An OS kernel runs in?",["User mode","Kernel mode","Both modes","No special mode"],1),
      _q("os-e-9","Paging eliminates?",["Internal fragmentation","External fragmentation","Both","Neither"],1),
      _q("os-e-10","A system call transitions execution from?",["Kernel mode to user mode","User mode to kernel mode","Process to thread","CPU to memory"],1),
      _q("os-e-11","What is a zombie process?",["A process with high CPU usage","A terminated process whose entry remains in process table","A process waiting for I/O","An orphan process"],1),
      _q("os-e-12","The PCB (Process Control Block) stores?",["Source code","Process state, registers, PID, memory info","Only PID","File content"],1),
      _q("os-e-13","Which memory allocation avoids external fragmentation?",["Contiguous allocation","Paging","Segmentation","Dynamic partitioning"],1),
      _q("os-e-14","Busy waiting wastes?",["Memory","Disk I/O","CPU cycles","Network bandwidth"],2),
      _q("os-e-15","An interrupt is handled by?",["User program","Interrupt Service Routine (ISR)","Scheduler","Compiler"],1),
      _q("os-e-16","Logical address is converted to physical address by?",["Compiler","MMU (Memory Management Unit)","OS scheduler","Cache"],1),
      _q("os-e-17","Which page replacement algorithm suffers from Belady's anomaly?",["LRU","Optimal","FIFO","LFU"],2),
      _q("os-e-18","A mutex lock can be acquired by?",["Any thread","Only one thread at a time","Multiple threads simultaneously","Only the OS"],1),
      _q("os-e-19","Spooling in OS is used for?",["CPU scheduling","Managing slow I/O devices like printers","Memory paging","Network communication"],1),
      _q("os-e-20","Process creation in Unix uses?",["spawn()","fork()","create()","exec()"],1),
    ],
    "Medium": [
      _q("os-m-1","Copy-on-write in fork() helps by?",["Copying all memory immediately","Sharing pages until write triggers copy","Avoiding page faults entirely","Disabling virtual memory"],1),
      _q("os-m-2","Which condition is NOT required for deadlock?",["Mutual exclusion","Hold and wait","Pre-emption allowed","Circular wait"],2),
      _q("os-m-3","Page table maps?",["Virtual addresses to physical frames","Physical to virtual","Process ID to memory","Files to blocks"],0),
      _q("os-m-4","TLB (Translation Lookaside Buffer) is?",["A type of RAM","Cache for recent virtual-to-physical address translations","A page table","A scheduling queue"],1),
      _q("os-m-5","The Banker's algorithm is used for?",["Memory allocation","Deadlock avoidance","CPU scheduling","Disk scheduling"],1),
      _q("os-m-6","Which scheduling algorithm minimizes average waiting time?",["FCFS","Round Robin","SJF (Shortest Job First)","Priority"],2),
      _q("os-m-7","Segmentation provides?",["Fixed-size memory chunks","Variable-size logical divisions matching program structure","No memory protection","Only physical addresses"],1),
      _q("os-m-8","IPC mechanisms include?",["Pipes, shared memory, message queues","Only pipes","Only sockets","Only signals"],0),
      _q("os-m-9","A race condition occurs when?",["Program runs too fast","Output depends on non-deterministic ordering of concurrent operations","Memory is full","CPU is idle"],1),
      _q("os-m-10","The critical section problem requires?",["Mutual exclusion, progress, bounded waiting","Only mutual exclusion","Only bounded waiting","Only progress"],0),
      _q("os-m-11","Working set model is related to?",["CPU scheduling","Thrashing prevention by tracking recently used pages","Disk management","Network I/O"],1),
      _q("os-m-12","Demand paging loads pages?",["All at start","Only when accessed (on page fault)","Based on prediction","Randomly"],1),
      _q("os-m-13","A monitor in concurrency provides?",["Shared variables only","Mutual exclusion with condition variables built-in","Semaphore emulation only","Spinlocks"],1),
      _q("os-m-14","Disk scheduling algorithm minimizing seek time is?",["FCFS","SCAN (Elevator)","Random","LIFO"],1),
      _q("os-m-15","An orphan process is?",["A process with no threads","A child process whose parent has died","A zombie process","A process with no memory"],1),
      _q("os-m-16","Multi-level feedback queue scheduling?",["Uses fixed priority","Dynamically adjusts priority based on behavior","Never preempts","Uses only one queue"],1),
      _q("os-m-17","What does exec() do in Unix?",["Creates a new process","Replaces current process image with a new program","Kills a process","Clones a process"],1),
      _q("os-m-18","Readers-writers problem allows?",["Only one reader at a time","Multiple concurrent readers but exclusive writers","Multiple concurrent writers","No concurrency"],1),
      _q("os-m-19","False sharing in cache occurs when?",["Two CPUs access the same variable","Different variables on same cache line cause contention","Cache is too small","TLB misses are frequent"],1),
      _q("os-m-20","The dining philosophers problem illustrates?",["CPU scheduling","Deadlock and resource contention","Memory allocation","I/O management"],1),
    ],
    "Hard": [
      _q("os-h-1","Memory-mapped I/O maps device registers to?",["Disk sectors","Virtual address space","CPU registers","Network buffers"],1),
      _q("os-h-2","Lock-free algorithms guarantee?",["No context switches","System-wide progress even if a thread stalls","Deadlock prevention","O(1) operations"],1),
      _q("os-h-3","CAS (Compare-And-Swap) is used to?",["Swap two processes","Atomically update a value if it matches expected","Lock a mutex","Prevent page faults"],1),
      _q("os-h-4","NUMA (Non-Uniform Memory Access) means?",["All memory is equal distance","Memory access time depends on memory location relative to processor","Memory is virtual","No memory hierarchy"],1),
      _q("os-h-5","Kernel-level threads vs user-level threads: kernel-level threads?",["Are faster to create","Allow true parallelism on multi-core systems","Cannot block","Use less memory"],1),
      _q("os-h-6","Memory barriers ensure?",["Physical memory boundaries","Instruction and memory operation ordering across CPUs","Cache invalidation","Page faults"],1),
      _q("os-h-7","The ABA problem in lock-free programming occurs when?",["A value changes from A to B then back to A, fooling a CAS","A deadlock involves 3 threads","Memory is exhausted","Spinlock loops forever"],0),
      _q("os-h-8","Huge pages benefit workloads by?",["Using less RAM","Reducing TLB misses for large memory allocations","Faster context switch","Preventing thrashing"],1),
      _q("os-h-9","Priority inversion happens when?",["High priority task is preempted by equal priority","Low-priority task holds a lock needed by high-priority task","Scheduler assigns wrong priority","Two tasks have same priority"],1),
      _q("os-h-10","The O(1) scheduler in Linux achieved O(1) scheduling by?",["Sorting the run queue","Using two fixed-size priority arrays for active and expired tasks","Using a heap","Binary search"],1),
      _q("os-h-11","Copy-on-write fork in a write-heavy workload causes?",["No overhead","High page fault rate as pages are copied on first write","Deadlocks","Segmentation faults"],1),
      _q("os-h-12","Vectored I/O (scatter-gather) allows?",["Writing to multiple disks simultaneously","Single syscall to read/write multiple non-contiguous buffers","Only reads","Only writes"],1),
      _q("os-h-13","io_uring in Linux reduces overhead by?",["Using more system calls","Submitting I/O requests via shared ring buffers without syscalls per I/O","Using kernel threads","Polling continuously"],1),
      _q("os-h-14","ASLR (Address Space Layout Randomization) prevents?",["Fragmentation","Buffer overflow exploits by randomizing memory layout","Race conditions","Deadlocks"],1),
      _q("os-h-15","mmap() is preferred over read() for large files because?",["It is simpler","It maps file directly into virtual memory avoiding double buffering","It is always faster","It uses less memory"],1),
      _q("os-h-16","Transparent huge pages can cause?",["Faster performance always","Latency spikes during compaction/defragmentation","Less memory usage","No side effects"],1),
      _q("os-h-17","Scheduler affinity sets?",["Process priority","Which CPUs a process prefers or is restricted to","Memory limits","I/O bandwidth"],1),
      _q("os-h-18","The epoch-based reclamation (EBR) technique is used for?",["Garbage collection in managed languages","Safe memory reclamation in lock-free data structures","Page reclamation","TLB flush"],1),
      _q("os-h-19","Userspace networking (DPDK) bypasses the kernel for?",["Memory management","High-performance packet processing without kernel overhead","CPU scheduling","File I/O"],1),
      _q("os-h-20","eBPF allows?",["Modifying kernel source","Running sandboxed programs in kernel space for observability and networking","Bypassing memory protection","Creating user threads in kernel"],1),
    ],
  },
  "Computer Networks": {
    "Easy": [
      _q("cn-e-1","TCP guarantees delivery via?",["Checksums only","Acknowledgments and retransmission","UDP fallback","IP routing"],1),
      _q("cn-e-2","DNS translates?",["IP to MAC","Domain name to IP address","Port to service","HTTP to HTTPS"],1),
      _q("cn-e-3","HTTP operates at which OSI layer?",["Network (3)","Transport (4)","Session (5)","Application (7)"],3),
      _q("cn-e-4","TCP 3-way handshake steps are?",["SYN, SYN-ACK, ACK","ACK, SYN, ACK","SYN, ACK, SYN","CONNECT, ACCEPT, OK"],0),
      _q("cn-e-5","TLS provides?",["Routing","Encryption, authentication, integrity","Load balancing","IP assignment"],1),
      _q("cn-e-6","UDP is preferred when?",["Reliability is critical","Low latency is more important than guaranteed delivery","Security is needed","Connection must be persistent"],1),
      _q("cn-e-7","The default HTTP port is?",["443","21","80","22"],2),
      _q("cn-e-8","A MAC address is at which OSI layer?",["Layer 1","Layer 2","Layer 3","Layer 4"],1),
      _q("cn-e-9","What does DHCP do?",["Resolves domain names","Dynamically assigns IP addresses","Routes packets","Encrypts traffic"],1),
      _q("cn-e-10","A subnet mask /24 has how many host bits?",["8","16","24","32"],0),
      _q("cn-e-11","HTTPS uses port?",["80","443","21","22"],1),
      _q("cn-e-12","ARP resolves?",["Domain name to IP","IP address to MAC address","MAC to port","URL to IP"],1),
      _q("cn-e-13","Which protocol sends email?",["POP3","IMAP","SMTP","FTP"],2),
      _q("cn-e-14","A router operates at OSI layer?",["1","2","3","4"],2),
      _q("cn-e-15","Bandwidth is measured in?",["Milliseconds","Bits per second","Packets per second","Bytes"],1),
      _q("cn-e-16","What is a packet?",["A full file","A chunk of data with header info for routing","An IP address","A TCP connection"],1),
      _q("cn-e-17","Which protocol is connectionless?",["TCP","FTP","UDP","SSH"],2),
      _q("cn-e-18","A firewall filters traffic based on?",["Only IP addresses","Rules about ports, IPs, protocols","Encryption keys","MAC addresses only"],1),
      _q("cn-e-19","Latency is?",["Bandwidth capacity","Time for a packet to travel from source to destination","Number of packets per second","Connection speed"],1),
      _q("cn-e-20","NAT (Network Address Translation) allows?",["Multiple private IPs to share one public IP","Encrypting traffic","Faster routing","DNS resolution"],0),
    ],
    "Medium": [
      _q("cn-m-1","HTTP/2 improves over HTTP/1.1 by?",["Removing TLS","Multiplexing multiple requests over one connection","Using UDP","Removing headers"],1),
      _q("cn-m-2","CDN reduces latency by?",["Faster CPUs","Serving content from edge nodes near users","Bigger pipes","Compressing DNS"],1),
      _q("cn-m-3","Exponential backoff prevents?",["Data corruption","Thundering herd and retry storms","Packet loss","TLS errors"],1),
      _q("cn-m-4","SSL/TLS handshake involves?",["Only key exchange","Certificate verification, key exchange, and cipher negotiation","Only encryption","Only authentication"],1),
      _q("cn-m-5","TCP flow control uses?",["TTL field","Sliding window to match sender speed to receiver buffer","Checksums","Sequence numbers only"],1),
      _q("cn-m-6","BGP is used for?",["LAN routing","Inter-AS routing on the internet","DNS resolution","TLS negotiation"],1),
      _q("cn-m-7","What causes TCP head-of-line blocking?",["Packet loss stalls all subsequent data until retransmitted","Large packets","High bandwidth","Slow DNS"],0),
      _q("cn-m-8","Anycast routing sends packets to?",["All nodes in a group","Nearest node in a group by routing metric","A random node","A specific node"],1),
      _q("cn-m-9","OSPF is a?",["Distance-vector protocol","Link-state routing protocol","Application layer protocol","Transport protocol"],1),
      _q("cn-m-10","Connection pooling in databases reduces?",["Query time","Overhead of establishing new TCP connections repeatedly","Memory usage","Disk I/O"],1),
      _q("cn-m-11","SNI (Server Name Indication) allows?",["Multiple SSL certs on one IP by sending hostname in TLS handshake","Faster TLS","IP masking","Certificate caching"],0),
      _q("cn-m-12","A SYN flood attack exploits?",["Buffer overflows","Half-open TCP connections exhausting server resources","DNS cache","HTTP headers"],1),
      _q("cn-m-13","Content negotiation in HTTP uses which header?",["Content-Type","Accept","Authorization","Cache-Control"],1),
      _q("cn-m-14","Nagle's algorithm in TCP?",["Increases throughput by batching small packets","Disables buffering","Sets timeout","Handles retransmission"],0),
      _q("cn-m-15","WebSocket differs from HTTP by?",["Using UDP","Providing full-duplex persistent connection over TCP","Encrypting automatically","Being stateless"],1),
      _q("cn-m-16","Zero-copy networking improves performance by?",["Using faster CPUs","Moving data directly from kernel buffer to NIC without CPU copies","Compressing packets","Reducing MTU"],1),
      _q("cn-m-17","A reverse proxy is placed?",["In front of clients","In front of backend servers to distribute requests","On DNS servers","At the ISP level"],1),
      _q("cn-m-18","QUIC protocol runs over?",["TCP","UDP","SCTP","Raw IP"],1),
      _q("cn-m-19","Consistent hashing minimizes?",["Cache misses","Keys remapped when a node is added or removed","Latency spikes","Bandwidth usage"],1),
      _q("cn-m-20","HTTP/3 uses QUIC instead of TCP to address?",["Security","Head-of-line blocking at transport layer","DNS latency","Certificate issues"],1),
    ],
    "Hard": [
      _q("cn-h-1","QUIC achieves 0-RTT connection resumption by?",["Pre-established keys cached from prior sessions","Skipping TLS","Using UDP only","Persistent TCP"],0),
      _q("cn-h-2","ECMP (Equal-Cost Multi-Path) routing?",["Prefers one path","Distributes traffic across multiple equal-cost paths","Uses BGP only","Applies to LANs only"],1),
      _q("cn-h-3","TCP CUBIC congestion control uses?",["Linear increase","Cubic function to probe bandwidth more aggressively after recovery","Fixed window","RTT only"],1),
      _q("cn-h-4","Anycast vs multicast: anycast delivers to?",["All members","Nearest member","A specific member","Random member"],1),
      _q("cn-h-5","BBR (Bottleneck Bandwidth and RTT) congestion control differs from CUBIC by?",["Being loss-based","Modeling the network rather than reacting to packet loss","Using UDP","Requiring kernel changes"],1),
      _q("cn-h-6","Tail latency matters because?",["Average hides outliers hurting user experience","It is easy to optimize","It applies only to UDP","It only affects TCP"],0),
      _q("cn-h-7","In a 3-node Raft cluster, minimum nodes for quorum are?",["1","2","3","All 3"],1),
      _q("cn-h-8","TCP TIME_WAIT state lasts?",["1 second","2*MSL (Maximum Segment Lifetime) to prevent delayed segments from corrupting new connections","Until explicit close","Until next packet"],1),
      _q("cn-h-9","SR-IOV allows?",["Software routing","NIC to present multiple virtual functions directly to VMs bypassing hypervisor","Encrypted networking","BGP routing"],1),
      _q("cn-h-10","Path MTU discovery avoids?",["DNS failures","IP fragmentation by finding smallest MTU on path","TCP retransmission","TLS overhead"],1),
      _q("cn-h-11","DCCP is designed for?",["Reliable file transfer","Congestion-controlled datagram service for real-time apps","Routing","DNS"],1),
      _q("cn-h-12","BGP hijacking is mitigated by?",["Firewalls","RPKI (Resource Public Key Infrastructure) validating route origins","Encryption","Bigger pipes"],1),
      _q("cn-h-13","Multi-path TCP (MPTCP) allows?",["One TCP connection across multiple network interfaces simultaneously","Faster single-path TCP","UDP replacement","HTTP/3 only"],0),
      _q("cn-h-14","In datacenter networking, ECMP hashing can cause?",["Even distribution always","Hash collisions creating hot spots","BGP flaps","DNS failures"],1),
      _q("cn-h-15","TCP receive buffer tuning matters because?",["It sets MTU","Window size limits throughput on high-BDP links (bandwidth-delay product)","It affects DNS","It sets TTL"],1),
      _q("cn-h-16","Segment Routing (SR) simplifies?",["DNS","MPLS-style traffic engineering using only source routing headers","TLS","UDP encapsulation"],1),
      _q("cn-h-17","In service mesh, the sidecar proxy handles?",["Business logic","mTLS, retries, circuit breaking transparent to the application","Database queries","DNS"],1),
      _q("cn-h-18","Why is UDP preferred for DNS?",["It is more reliable","Low overhead for small request-response that fits in one packet","It is encrypted","It supports streaming"],1),
      _q("cn-h-19","VXLAN encapsulates?",["IP in IP","Layer 2 frames in UDP packets for overlay networking","TCP in UDP","QUIC in TCP"],1),
      _q("cn-h-20","Connection draining in load balancers?",["Kills connections immediately on deregister","Allows in-flight requests to complete before removing a backend","Resets TCP","Blocks new connections permanently"],1),
    ],
  },
  "OOP & Design": {
    "Easy": [
      _q("oop-e-1","Encapsulation means?",["Hiding implementation behind a public interface","Inheriting from base class","Overriding methods","Creating many instances"],0),
      _q("oop-e-2","Polymorphism allows?",["Multiple inheritance only","One interface, many implementations","Faster execution","Memory sharing"],1),
      _q("oop-e-3","The Liskov Substitution Principle states?",["Subclasses must override all methods","Subclasses should substitute base class without breaking behaviour","Interfaces must be small","Classes should not depend on modules"],1),
      _q("oop-e-4","Single Responsibility Principle means a class should have?",["Many responsibilities","Only one reason to change","No inheritance","Static methods only"],1),
      _q("oop-e-5","The Observer pattern is used for?",["Creating objects","One-to-many event notification","Caching","Database access"],1),
      _q("oop-e-6","Interface vs Abstract class: an interface?",["Can have implementation","Cannot be instantiated","Can store state","Extends only one class"],1),
      _q("oop-e-7","Constructor is used to?",["Destroy an object","Initialize an object when created","Call parent methods","Override behaviour"],1),
      _q("oop-e-8","Inheritance promotes?",["Code duplication","Code reuse via parent-child relationship","Encapsulation","Loose coupling"],1),
      _q("oop-e-9","The Factory pattern creates objects?",["Directly with new","Through a factory method hiding creation logic","Via dependency injection","Using a singleton"],1),
      _q("oop-e-10","Abstraction means?",["Hiding all code","Exposing only essential features, hiding details","Copying a class","Making all fields public"],1),
      _q("oop-e-11","A Singleton ensures?",["Multiple instances","Only one instance of a class exists","Fast creation","Thread safety always"],1),
      _q("oop-e-12","Method overloading differs from overriding in that overloading uses?",["Different method names","Same name with different parameters in same class","Inheritance","Interfaces"],1),
      _q("oop-e-13","Open/Closed Principle states classes should be?",["Open for modification only","Closed for extension only","Open for extension, closed for modification","Open for both"],2),
      _q("oop-e-14","A UML class diagram shows?",["Runtime behaviour","Static structure: classes, attributes, relationships","Database schema","Network topology"],1),
      _q("oop-e-15","Dependency Inversion Principle says high-level modules should depend on?",["Concrete implementations","Abstractions (interfaces)","Low-level modules","Singletons"],1),
      _q("oop-e-16","An abstract method?",["Has a body","Must be overridden in subclass","Cannot be called","Returns void"],1),
      _q("oop-e-17","The Decorator pattern?",["Creates objects","Adds behaviour at runtime by wrapping objects","Manages database connections","Notifies observers"],1),
      _q("oop-e-18","Coupling refers to?",["How a class is tested","Degree of interdependence between classes","Number of methods","Lines of code"],1),
      _q("oop-e-19","A pure virtual function in C++ means the class is?",["Concrete","Abstract","Static","Final"],1),
      _q("oop-e-20","Composition over inheritance is preferred because?",["Composition is faster","It avoids tight coupling and fragile base class problems","Inheritance is deprecated","Composition uses less memory"],1),
    ],
    "Medium": [
      _q("oop-m-1","Dependency Injection helps with?",["Faster I/O","Testability by removing hard-coded dependencies","Thread safety","Memory allocation"],1),
      _q("oop-m-2","Strategy pattern lets you?",["Create complex objects step by step","Swap algorithms at runtime","Wrap legacy interfaces","Cache computations"],1),
      _q("oop-m-3","The Command pattern is useful for?",["Dependency injection","Encapsulating requests as objects (undo, queue, log)","Type safety","Sorting"],1),
      _q("oop-m-4","Which SOLID principle does Interface Segregation address?",["Not forcing clients to depend on interfaces they don't use","Single responsibility","Open/closed","Dependency inversion"],0),
      _q("oop-m-5","The Facade pattern provides?",["Complex interface to subsystem","Simplified interface to complex subsystem","Caching","Event notification"],1),
      _q("oop-m-6","Cohesion measures?",["Dependency between classes","How related and focused a class's responsibilities are","Number of methods","Lines of code"],1),
      _q("oop-m-7","The Template Method pattern?",["Creates objects","Defines algorithm skeleton; subclasses fill in steps","Notifies observers","Manages resources"],1),
      _q("oop-m-8","Lazy initialization means?",["Initializing in constructor","Delaying creation until first use","Creating in static block","Never initializing"],1),
      _q("oop-m-9","Which pattern is best for a plugin architecture?",["Singleton","Factory / Abstract Factory","Observer","Proxy"],1),
      _q("oop-m-10","The Proxy pattern can be used for?",["Only caching","Access control, caching, logging, or lazy loading","Only logging","Only lazy loading"],1),
      _q("oop-m-11","Builder pattern is used when?",["Object has one parameter","Object has many optional parameters making constructors complex","Performance is critical","Thread safety is needed"],1),
      _q("oop-m-12","Double-checked locking in Singleton is used for?",["Performance","Thread-safe lazy initialization with minimal synchronization overhead","Memory saving","Error handling"],1),
      _q("oop-m-13","The Repository pattern separates?",["View from model","Data access logic from business logic","Controller from view","Service from DTO"],1),
      _q("oop-m-14","Anemic domain model anti-pattern means?",["Domain objects have too much logic","Domain objects are data containers with logic in service classes","Models are too large","Models use inheritance"],1),
      _q("oop-m-15","Which pattern converts one interface to another?",["Facade","Adapter","Decorator","Proxy"],1),
      _q("oop-m-16","Immutable objects are thread-safe because?",["They use locks","Their state never changes after creation","They are singletons","They use volatile fields"],1),
      _q("oop-m-17","The Chain of Responsibility pattern passes requests?",["To all handlers","Along a chain until one handles it","Only to first handler","To a random handler"],1),
      _q("oop-m-18","Service Locator vs Dependency Injection: DI is preferred because?",["DI is faster","DI makes dependencies explicit and testable; SL hides them","DI uses less memory","SL is deprecated"],1),
      _q("oop-m-19","God Object anti-pattern is a class that?",["Has perfect cohesion","Does too much, violating SRP","Has no methods","Uses too many patterns"],1),
      _q("oop-m-20","Event-driven architecture decouples components using?",["Direct method calls","Events and message brokers","Shared databases","RPC"],1),
    ],
    "Hard": [
      _q("oop-h-1","CQRS separates?",["Classes and interfaces","Read models from write models","Frontend from backend","Testing from production"],1),
      _q("oop-h-2","Event sourcing stores?",["Current state only","Full event log as the source of truth","SQL snapshots","Compressed diffs"],1),
      _q("oop-h-3","Hexagonal architecture (Ports & Adapters) isolates?",["Database only","Domain logic from infrastructure using port interfaces","View from controller","Tests from code"],1),
      _q("oop-h-4","Domain-Driven Design's Bounded Context defines?",["A microservice always","Explicit boundary within which a domain model applies","A database","A team"],0),
      _q("oop-h-5","The Visitor pattern allows?",["Adding new operations to object hierarchy without modifying existing classes","Creating objects","Caching","Proxying"],0),
      _q("oop-h-6","Reactive programming handles?",["Synchronous operations","Asynchronous data streams with backpressure","Thread management","Database transactions"],1),
      _q("oop-h-7","Saga pattern in microservices manages?",["Database schemas","Distributed transactions using compensating transactions","Service discovery","Load balancing"],1),
      _q("oop-h-8","The Specification pattern encapsulates?",["Object creation","Business rules as composable objects","Data access","Event handling"],1),
      _q("oop-h-9","Aggregate in DDD is?",["Any class","Cluster of objects treated as unit with one root for consistency","A repository","A service"],1),
      _q("oop-h-10","Outbox pattern solves?",["Database scaling","Dual-write inconsistency between DB and message broker","Cache invalidation","Schema migration"],1),
      _q("oop-h-11","Transactional outbox ensures?",["Messages are sent exactly once atomically with DB write","Faster messaging","No message broker needed","Synchronous communication"],0),
      _q("oop-h-12","Actor model concurrency uses?",["Shared mutable state with locks","Isolated actors communicating via messages","Thread pools","Semaphores"],1),
      _q("oop-h-13","Microkernel architecture separates?",["Core functionality from plugins/extensions","Frontend from backend","Tests from code","Read from write"],0),
      _q("oop-h-14","Strangler Fig pattern is used for?",["New greenfield systems","Gradually replacing legacy system with new one","Performance optimization","Database migration"],1),
      _q("oop-h-15","Type erasure in generics means?",["Types are checked at runtime","Generic type parameters are removed at compile time","Types are duplicated","No type safety"],1),
      _q("oop-h-16","The Flyweight pattern reduces memory by?",["Deleting objects","Sharing common state among many fine-grained objects","Lazy loading","Caching only"],1),
      _q("oop-h-17","Inversion of Control differs from Dependency Injection in that IoC is?",["Narrower","The broader principle; DI is one implementation of IoC","Slower","Unrelated"],1),
      _q("oop-h-18","Why is the Singleton pattern considered problematic in testing?",["It is too fast","It introduces global state making tests order-dependent","It uses too much memory","It prevents inheritance"],1),
      _q("oop-h-19","Functional core, imperative shell architecture means?",["All code is functional","Pure functions handle logic; side effects are at edges","OOP is avoided","No classes"],1),
      _q("oop-h-20","Protocol Buffers vs JSON: protobuf is preferred when?",["Human readability is priority","High throughput and schema enforcement are needed","JavaScript is used","Debugging is frequent"],1),
    ],
  },
}


def quiz_topics() -> list[str]:
    return list(BANK.keys())


def quiz_difficulties(topic: str) -> list[str]:
    return list(BANK.get(topic, {}).keys())


def quiz_questions(topic: str, difficulty: str) -> list[dict]:
    return BANK.get(topic, {}).get(difficulty, [])
